steps:
  - id: "Build web frontend image"
    name: "gcr.io/cloud-builders/docker"
    entrypoint: 'bash'
    args:
    - '-c'
    - |
      docker build . -t ${_MULTIREGION}-docker.pkg.dev/${PROJECT_ID}/dronegaga-artifact-registry/web
      docker push ${_MULTIREGION}-docker.pkg.dev/${PROJECT_ID}/dronegaga-artifact-registry/web

substitutions:
    _MULTIREGION: us # default value

options:
  logging: CLOUD_LOGGING_ONLY